[[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 1

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "相册"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "照片"
  url = "gallery/photo"

[[main]]
  identifier = "about"
  name = "关于" 
  url = "about"
  weight = 4

#[[main]]
#  identifier = "presentation"
#  name = "文档展示"
#  url = "presentation"
#  weight = 5

#[[main]]
#  identifier = "showcase"
#  name = "成品展示"
#  url = "showcase"
#  weight = 6

#[[main]]
#  identifier = "publication"
#  name = "发布"
#  url = "publication"
#  weight = 7